FROM node:22-slim AS builder
WORKDIR /usr/src/app
COPY package.json .
COPY package-lock.json* .
RUN npm ci

FROM node:22-slim
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ /usr/src/app/
COPY . .

# CMD ["pwd"]
# CMD ["ls", "-la", "content"]
CMD ["npx", "quartz", "build", "--serve"]
